name: Build Flutter Application

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          cache: true
      - name: Build and Upload Windows artifact
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release
          Compress-Archive -Path .\build\windows\x64\runner\Release\ -DestinationPath .\launsh-windows-x64-${env:GITHUB_REF_NAME}.zip
          gh release upload --clobber "${GITHUB_REF_NAME}" "launsh-windows-x64-${env:GITHUB_REF_NAME}.zip"

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          cache: true
      - name: Build and Upload macOS artifact
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          flutter pub get
          flutter build macos --release
          zip launsh-macos-${GITHUB_REF_NAME}.zip build/macos/Build/Products/Release/launsh.app
          gh release upload --clobber "${GITHUB_REF_NAME}" "launsh-macos-${GITHUB_REF_NAME}.zip"
